add sensor_xxx variables description
opengisch/QField-docs pull request #114
Opened 2021-01-20 14:43 UTC by mbernasocchi

Relates to https://github.com/opengisch/QField/pull/1608/

2021-01-20 15:13 UTC, m-kuhn commented
I guess for most cases the `@position_xxx` variables are more appropriate than the sensor ones, I think these should be the most prominent ones.

2021-01-20 15:14 UTC, m-kuhn requested changes
Use `position_xxx` as the main documentation

2021-01-27 08:52 UTC, m-kuhn commented on en/prepare/attributes-form.rst
> +All @position_* variables have a corresponding @gnss_* variable. The sensor variables always report the gnss sensor values.
```suggestion
All @position_* variables have a corresponding @gnss_* variable. The gnss variables always report the gnss sensor values, even when the crosshair is not snapped.
```

2021-01-27 08:52 UTC, m-kuhn approved these changes
good work

2021-01-27 08:57 UTC, LindaOPENGIS approved these changes

2021-01-27 08:57 UTC, LindaOPENGIS commented on en/prepare/attributes-form.rst
> +All @position_* variables have a corresponding @gnss_* variable. The gnss variables always report the gnss sensor values, even when the crosshair is not snapped.
```suggestion
All @position_* variables have a corresponding @gnss_* variable. The @gnss_* variables always report the gnss sensor values, even when the crosshair is not snapped.
```

2021-01-27 08:57 UTC, merged

2021-01-27 08:58 UTC, m-kuhn commented
Sorry, I was a bit too fast with merging, you can open a new pull request

2021-01-27 09:00 UTC, mbernasocchi commented
no worries, I was showing Linda how to insert suggestions :)