Added the section of Offliner packager
opengisch/QField-docs pull request #412
Opened 2024-01-31 19:44 UTC by SeqLaz

Added the section of the new functionality of Offliner packager

2024-01-31 19:44 UTC, duke-nyuki commented
Task linked: [QF-3790 Added offliner configuration to the project settings form by @suricactus in #524](https://app.clickup.com/t/2192114/QF-3790)

2024-02-01 15:53 UTC, faebebin commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +   - The new offliner configuration optimizes storage by consolidating filtered layers using the same datasource, enhancing efficiency in data management, and for apply distinct  symbology to the sam
```suggestion
   - The new offliner uses less storage by consolidating filtered layers into a single datasource respecting distinct symbology.
```

2024-02-01 15:54 UTC, faebebin commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +   - The Packaging Offliner is designed to package data for offline use with QField. For new projects, it is recommended to use the "Optimized Packager" over the deprecated "QGIS Core Offline Editing
```suggestion


```
this i would discard

2024-02-01 16:14 UTC, faebebin requested changes
@SeqLaz thanks alot for this.

I just made some rewording suggestions.

For correctness please @suricactus please check :)

Many thanks

2024-02-01 16:14 UTC, faebebin commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +The new Packaging Offliner (in "Settings" of your projects) introduces advanced capabilities, allowing the support of multiple layers using the same data source but with distinct filters. This enhanc
```suggestion
For new projects, it is recommended to use the new "Optimized Packager" over the deprecated "QGIS Core Offline Editing". Set it under "Packaging Offliner" in the "Settings" tab of your project. The "Optimized Packager" supports consolidating filtered layers of same datasource into a single oflline layer, respecting distinct symbology. This also uses less storage. Here's an example to illustrate this feature:
```

2024-02-01 16:14 UTC, faebebin commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +   - The Packaging Offliner is designed to package data for offline use with QField. For new projects, it is recommended to use the "Optimized Packager" over the deprecated "QGIS Core Offline Editing
```suggestion

```
I would drop this

2024-02-06 13:23 UTC, suricactus approved these changes

2024-02-06 13:25 UTC, suricactus commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +For new projects, it is recommended to use the new "Optimized Packager" over the deprecated "QGIS Core Offline Editing". Set it under "Packaging Offliner" in the "Settings" tab of your project. The "
```suggestion
We recommend to use the new "Optimized Packager" over the deprecated "QGIS Core Offline Editing" for all your projects. Set the packager under "Packaging Offliner" in the "Settings" tab of your project.

The "Optimized Packager" supports consolidating filtered layers of same datasource into a single oflline layer, respecting distinct symbology but also using less storage. Here's an example to illustrate this feature:
```

2024-02-06 13:36 UTC, faebebin approved these changes

2024-02-06 13:37 UTC, faebebin commented
many thanks

2024-02-06 14:34 UTC, merged