get-started-storage
opengisch/QField-docs pull request #485
Opened 2024-07-24 12:21 UTC by earlgray1979

This pull request proposes restructuring the get-started/storage.en.md, as well as adding crosslinks and elaborating on different methods on how to
- Export and package files from QGIS for use in QField
- OS-specific importing of project data into QField

The proposed changes only go up to the section **Exporting modified projects and datasets** (line 205). More pushes will follow.

2025-03-17 08:49 UTC, beanzmo requested changes
This could do with a few more images but it has significantly improved

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +How to set up and work with QFieldCloud is explained in the next chapter.
```suggestion
On the QField homescreen, users are presented with two options to open a project.

 **QFieldCloud projects**: The first option is to [access a project stored on QFieldCloud](../get-started/index.en.md)
How to set up and work with QFieldCloud is explained in the next chapter.

* **Open local file**: The second option involves copying a working copy of the project file from a laptop or PC (the source device), on to the phone or tablet (the target device).
On the target device, users can access and edit this local copy using QField, and eventually copy the new version back to the desktop or to an alternative cloud storage service. How to prepare, store and access these local copies is the topic of this chapter.

```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +    Instructions below should help users' adjust to the new circumstances.
Can this not be deleted by now?

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +There are three ways of preparing and copying a project in QGIS for use in QField.
```suggestion
QFieldQField supports a [wide range of data formats](../reference/data-format.en.md).
There are three ways of preparing and copying a project in QGIS for use in QField.
```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +We recommend using the GeoPackage file format for projects in QField, since packaging in QGIS is easy and straightforward. To package a project as a GeoPackage, three steps are necessary.
```suggestion
The simplest and most efficient way to package a QGIS project and its corresponding geospatial data into one file is to use [GeoPackages](https://www.geopackage.org/).
We recommend using the GeoPackage file format for projects in QField, since packaging in QGIS is easy and straightforward. To package a project as a GeoPackage, three steps are necessary.
```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +We recommend using the GeoPackage file format for projects in QField, since packaging in QGIS is easy and straightforward. To package a project as a GeoPackage, three steps are necessary.
@SeqLaz  Is that correct ? I thought the .qgz file should be rather outside of the gpkg?

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +For more information, consult the QGIS documentation for more information [packaging layers](https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/qgis/database.html#package-layers).
```suggestion
For more information, consult the QGIS documentation  [packaging layers](https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/qgis/database.html#package-layers).
```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +Another possibility is to store the project and its layers in a [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) database.
Is this recommended or should be avoided in which case I would probably mark that behind the sentence @SeqLaz

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +Changes done to project content and datasets are saved in the files found in this location.
```suggestion
Changes done to the project content and datasets are saved in the files found in this location.
```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +One workaround could be the following
```suggestion
Transfering files from MacBooks or Macs to iPhone using a cable is not straightforward, since it is not possible to access individual files in the QField directory.
One workaround could be the following
```

2025-03-17 08:49 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +On Android all of these actions are available by click on the ‘import (+) button‘ located on the bottom-right corner of the project/dataset picker screen, which can be accessed by clicking on the ‘Op
```suggestion
On Android all of these actions are available by clicking on the ‘import (+) button‘ located on the bottom-right corner of the project/dataset picker screen, which can be accessed by clicking on the ‘Open local files’ button located in QField‘s welcome screen.
```

2025-03-17 15:08 UTC, SeqLaz commented on documentation/get-started/storage.en.md
> +We recommend using the GeoPackage file format for projects in QField, since packaging in QGIS is easy and straightforward. To package a project as a GeoPackage, three steps are necessary.
Yes, that is correct. It should be saved as a .qgs/.qgz file and not in a GeoPackage. The GeoPackage should be for the layers.

2025-03-17 15:11 UTC, SeqLaz commented on documentation/get-started/storage.en.md
> +Another possibility is to store the project and its layers in a [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) database.
SpatiaLite is fully compatible. However, if possible, migrate the layers from SpatialLite to GeoPackage, as GeoPackage it is the recommended format for QField works!

2025-03-18 08:55 UTC, suricactus commented on documentation/get-started/storage.en.md
> +Another possibility is to store the project and its layers in a [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) database.
I would not put it in the docs, this is leftover from the :sauropod: era.

2025-04-08 01:22 UTC, dangomaps requested changes
I think we should remove line 12 to 23, what Google did in 2021 is no longer relevant for our documentation. 

Also I am confused about the references to the use of spatiallite databases should this be in the doc's

2025-04-08 01:30 UTC, dangomaps approved these changes

2025-04-08 03:49 UTC, dangomaps commented on documentation/get-started/storage.en.md
> +Another possibility is to store the project and its layers in a [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index) database.
```suggestion
```

2025-04-08 03:50 UTC, dangomaps commented on documentation/get-started/storage.en.md
>  !!! note
```suggestion
```

2025-04-08 03:51 UTC, dangomaps commented on documentation/get-started/storage.en.md
> +    Instructions below should help users' adjust to the new circumstances.
```suggestion
```

2025-04-08 03:52 UTC, dangomaps approved these changes

2025-04-08 03:58 UTC, nirvn commented on documentation/get-started/storage.en.md
> +QFieldQField supports a [wide range of data formats](../reference/data-format.en.md).
```suggestion
QFieldQField supports a [wide range of data formats](../reference/data-format/).
```

2025-04-08 03:59 UTC, nirvn commented on documentation/get-started/storage.en.md
> + **QFieldCloud projects**: The first option is to [access a project stored on QFieldCloud](../get-started/index.en.md)
```suggestion
 **QFieldCloud projects**: The first option is to [access a project stored on QFieldCloud](../get-started/)
```

2025-04-08 04:01 UTC, nirvn commented on documentation/get-started/storage.en.md
> +QFieldQField supports a [wide range of data formats](../reference/data-format/).
```suggestion
QFieldQField supports a [wide range of data formats](../reference/data-format).
```

2025-04-08 04:04 UTC, nirvn commented on documentation/get-started/storage.en.md
> +QFieldQField supports a [wide range of data formats](../reference/data-format).
```suggestion
QFieldQField supports a [wide range of data formats](../reference/data-format.md).
```

2025-04-12 07:59 UTC, beanzmo approved these changes

2025-04-16 08:28 UTC, beanzmo requested changes

2025-04-16 08:28 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +* [Packaging the project as a SpatiaLite database](###packaging-the-project-as-a-spatiaLite-database)
```suggestion
```

2025-04-25 12:16 UTC, beanzmo approved these changes

2025-04-25 12:16 UTC, beanzmo commented on documentation/get-started/storage.en.md
> +* [Packaging the project as a SpatiaLite database](###packaging-the-project-as-a-spatiaLite-database)
```suggestion
```

2025-04-25 12:16 UTC, merged