How to allow users to only push attachments to QFieldCloud
opengisch/QField-docs pull request #489
Opened 2024-08-14 18:29 UTC by SeqLaz

2024-08-28 13:03 UTC, nirvn reviewed
IMHO, this should be in the advanced setup. I spent some time recently to _remove_ information from the getting started page, which should remain as lean as possible and focused on getting people started with a simple project.

2024-08-28 13:03 UTC, nirvn commented on documentation/get-started/tutorials/get-started-qfc.en.md
> +To ensure that QField and QFieldCloud only synchronize attachments from your local QField instance to the cloud, you can control the synchronization settings. By leaving the Attachment directories un
```suggestion
When needed, it is possible to configure a cloud project to insure that attachments taken QField are uploaded to QFieldCloud and subsequently not synchronized back to other QField users. To achieve this result, insure that the Attachment directories list in the project properties dialog is empty by selecting preexisting directories and deleting them via the Del keyboard key.
```

2024-09-18 15:27 UTC, suricactus requested changes
@nirvn I think this documentation is incorrect. This functionality does not work as described. Actually the attachment dirs are used for something else.

Can you confirm I am looking at the right place? https://github.com/opengisch/QField/blob/master/src/core/qfieldcloudprojectsmodel.cpp#L1116-L1171

This PR describes functionality that we want, but is not yet implemented.

Also, it should not be in attributes-form.md IMO, but in "advanced setup".

2024-12-01 06:04 UTC, nirvn commented
Correct, my bad, I was spreading misinformation :cry:

2025-02-07 07:33 UTC, closed without merging